# Generated by Django 3.2.13 on 2026-02-15 18:32

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resource_management', '0001_initial'),
        ('pattern_engine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectationModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='resource_management.agentmodel')),
                ('trame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='pattern_engine.tramemodel')),
            ],
            options={
                'verbose_name': 'Affectation',
                'verbose_name_plural': 'Affectations',
                'unique_together': {('agent', 'trame', 'date_debut')},
            },
        ),
    ]
