# Generated by Django 6.0.2 on 2026-02-22 16:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applied_planning', '0001_initial'),
        ('resource_management', '0003_agentmodel_est_surnumeraire'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbsenceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('type_absence', models.CharField(choices=[('MALADIE', 'Maladie'), ('CONGE_PAYE', 'Congé Payé'), ('FORMATION', 'Formation'), ('AUTRE', 'Autre')], max_length=20)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='resource_management.agentmodel')),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
            },
        ),
    ]
