# Generated by Django 3.2.13 on 2026-02-15 19:01

from django.db import migrations
import resource_management.models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentmodel',
            name='quotite',
            field=resource_management.models.QuotiteField(default=1.0),
        ),
    ]
