# Generated by Django 6.0.2 on 2026-02-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0002_alter_agentmodel_quotite'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='est_surnumeraire',
            field=models.BooleanField(default=False),
        ),
    ]
