# Generated by Django 6.0.2 on 2026-03-01 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource_management', '0003_agentmodel_est_surnumeraire'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentmodel',
            name='base_horaire',
            field=models.FloatField(default=35.0),
        ),
        migrations.AddField(
            model_name='agentmodel',
            name='rtt_eligible',
            field=models.BooleanField(default=False),
        ),
    ]
