# Generated by Django 3.2.13 on 2026-02-15 18:34

import compliance_engine.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PolitiqueConformiteModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('regles_data', models.JSONField(default=list, encoder=compliance_engine.models.RegleEncoder)),
            ],
            options={
                'verbose_name': 'Politique de Conformité',
                'verbose_name_plural': 'Politiques de Conformité',
            },
        ),
    ]
