# Generated by Django 6.0.2 on 2026-02-19 18:03

import compliance_engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance_engine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='politiqueconformitemodel',
            name='regles_data',
            field=models.JSONField(decoder=compliance_engine.models.RegleJSONDecoder, default=list, encoder=compliance_engine.models.RegleEncoder),
        ),
    ]
