# Generated by Django 6.0.2 on 2026-02-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRequirementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], unique=True)),
                ('required_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Besoin Quotidien',
                'verbose_name_plural': 'Besoins Quotidiens',
            },
        ),
    ]
