# Generated by Django 3.2.13 on 2026-02-15 18:28

from django.db import migrations, models
import pattern_engine.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrameModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('duree_cycle_jours', models.IntegerField()),
                ('sequence_data', models.JSONField(default=list, encoder=pattern_engine.models.ShiftEncoder)),
            ],
            options={
                'verbose_name': 'Trame',
                'verbose_name_plural': 'Trames',
            },
        ),
    ]
